create table if not exists public.dashboard_support_responses (
  id bigint generated by default as identity primary key,
  ride_id uuid not null references public.rides(id) on delete cascade,
  created_by_account_id uuid references public.dashboard_accounts(id) on delete set null,
  created_by_username text not null,
  audience text not null check (audience in ('customer', 'driver', 'both', 'custom')),
  title text,
  body text not null,
  recipient_ids uuid[] not null default '{}'::uuid[],
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists dashboard_support_responses_ride_idx
  on public.dashboard_support_responses (ride_id, created_at desc);

alter table public.dashboard_support_responses enable row level security;

create table if not exists public.dashboard_support_thread_reads (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.dashboard_accounts(id) on delete cascade,
  ride_id uuid not null references public.rides(id) on delete cascade,
  last_seen_message_id bigint not null default 0,
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (account_id, ride_id)
);

create index if not exists dashboard_support_thread_reads_account_idx
  on public.dashboard_support_thread_reads (account_id, updated_at desc);

alter table public.dashboard_support_thread_reads enable row level security;

create or replace function public.handle_dashboard_support_response_signal()
returns trigger
language plpgsql
as $$
begin
  if to_regproc('public.dashboard_bump_section_signal') is not null then
    perform public.dashboard_bump_section_signal('support', TG_TABLE_NAME, 'global', null, 2);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_dashboard_support_response_signal on public.dashboard_support_responses;

create trigger trg_dashboard_support_response_signal
after insert on public.dashboard_support_responses
for each row
execute function public.handle_dashboard_support_response_signal();
